### ISSUE TITLE
sed usage bug

### ISSUE THREAD

**Issue by eigenlambda** [awslabs/serverless-bot-framework#1]
As specified on https://linux.die.net/man/1/sed , there isn't supposed to be a space between the -i option and its argument.  The sed in msys2 complains

sed: can't read : No such file or directory

as it assumes anything that isn't prefixed by an option is a filename.  Presumably the author's sed behaves differently, which is actually a fairly dangerous unix api bug, but is harmless here, since sed merely complains but doesn't do anything differently.

**Comment by thomasphorton** [comment]
We're building on Mac OS and Amazon Linux, where `-i` can take a null string to prevent a backup file from being created during in-place replacement. Do you have a proposed fix for this that will work for all versions of `sed`?

**Comment by jrbenito** [comment]
Simply use `sed -i -e ...` works on Linux.

**Comment by aassadza** [comment]
Addressed with version v1.1.0.

For sed in-place option, as in <code>sed -i -e ...</code>, we switched to using syntax that is compatible with GNU sed  POSIX, which comes with typical Linux distros. For macOS version of sed, you can change this back to <code>sed -i '' -e ...</code> in your environment.
