### ISSUE TITLE
SampleWebclientPackage typo

### ISSUE THREAD

**Issue by petersonwagner** [awslabs/serverless-bot-framework#3]
I believe that there's a typo in serverless-bot-framework/deployment/serverless-bot-framework.template, line 1308.

should be:
`
"SampleWebclientPackage": {
          "Fn::Join": [
            "", [
              `**`"https://s3."`**`,
              {
                "Ref": "AWS::Region"
              },
              ".amazonaws.com/",
              "%%BUCKET_NAME%%",
              "-",
              {
                "Ref": "AWS::Region"
              },
              "/serverless-bot-framework/%%VERSION%%/sample-webclient.zip"
            ]
          ]
        },
`

instead of:
`
"SampleWebclientPackage": {
          "Fn::Join": [
            "", [
              `**`"https://s3-"`**`,
              {
                "Ref": "AWS::Region"
              },
              ".amazonaws.com/",
              "%%BUCKET_NAME%%",
              "-",
              {
                "Ref": "AWS::Region"
              },
              "/serverless-bot-framework/%%VERSION%%/sample-webclient.zip"
            ]
          ]
        },
`

**Comment by tomnight** [comment]
HI peter, 
The links in the template is the region specific URL so s3- is valid although technically either way would work. details here:
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#create-bucket-intro

Thanks for the feedback.

**Comment by aassadza** [comment]
This is addressed with version v1.2.0. Thank you for your feedback.
