### ISSUE TITLE
READMe.md is wrong about AWS region

### ISSUE THREAD

**Issue by jrbenito** [awslabs/serverless-bot-framework#5]
Hi,

[README.md](https://github.com/awslabs/serverless-bot-framework/blame/master/README.md#L7) file  says that second parameter to the `build-s3-dist.sh`  is AWS region but inside script it is clear the deployment version.

**Comment by beomseoklee** [comment]
Hi,

Thanks for your comment, and I have confirmed you are right.
We will fix this one.

**Comment by aassadza** [comment]
Addressed with version v1.1.0
