### ISSUE TITLE
Usage of Lex

### ISSUE THREAD

**Issue by aboovv1976** [awslabs/serverless-bot-framework#7]
This is not really an issue but it is an enquiry. Various places it is mentioned that it uses Lex. But, in the architecture diagram or checking the services the stack installed, Lex is no where seen. I do understand that the solution does Natural Language Processing (NLP). How is it doing NLP if Lex is not in use?

**Comment by tabdunabi** [comment]
Hi @aboovv1976, thank you for reaching out and your inquiry about the NLP engine used by the serverless-bot-framework.
The serverless-bot-framewrok does not use AWS Lex. It uses a custom NLP engine, developed using standard NLP and ML algorithms. Detailed implementation can be found here  https://github.com/awslabs/serverless-bot-framework/tree/master/source/modules/b2.core.
The implementation guide (https://s3.amazonaws.com/solutions-reference/serverless-bot-framework/latest/serverless-bot-framework.pdf) explains (on page 5) how the ML model is trained. Appendix A (starting on page 13) goes into more details on algorithms used, how the bot can be trained for a specific use-case, and how the intents are identified by the bot.

**Comment by aboovv1976** [comment]
Thank for your comments!
